- alias: Set 'away' by hand
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'away'
  condition:
    - condition: template
      value_template: "{{ states('input_select.house_mode') != 'away' }}"
  action:
    - service: switch.turn_off
      entity_id:
        - group.lights
        - group.sockets
    - service: light.turn_off
      entity_id:
        - group.living_room_light_and_leds
        - group.master_bedroom_little_lights
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_04cf8cb87b01
        brightness_pct: 2
        color_name: red
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "François, mode away actif."
