#########################################################

- platform: ping
  name: ping TV
  host: 10.0.0.189
  count: 5
  scan_interval: 30

#########################################################
