#########################################################

- platform: workday
  country: DE
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2019-12-31'
    - '2020-01-01'

#########################################################
