#########################################################

- platform: workday
  country: DE
  excludes: [sat, sun, holiday]
  add_holidays:
    - '2019-12-24'
    - '2019-12-25'
    - '2019-12-26'
    - '2019-12-31'

#########################################################
