- alias: "button toogle cover"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033e8984
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_bedroom_1
