- platform: manual
  name: Home
  code: !secret alarm_code
  pending_time: 0
  delay_time: 20
  trigger_time: 4
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
  armed_away:
    pending_time: 0
    delay_time: 0
