#########################################################
# Home Assistant                                        #
#########################################################

homeassistant:
   elevation: 5
   latitude: 48.98160415046025
   longitude: 2.269970923662186
   name: 'Casa'
   time_zone: 'Europe/Paris'
   unit_system: 'metric'
   customize: !include_dir_merge_named customize

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: !secret base_url


# Text to speech
tts:
  - platform: google_translate
    language: 'fr'

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml

device_tracker: !include device_tracker.yaml
linky: !include linky.yaml
notify: !include notify.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
mqtt: !include mqtt.yaml
media_player: !include media_player.yaml
owntracks: !include owntracks.yaml
zone: !include zone.yaml

# third party
cover: !include cover.yaml
rfxtrx:
  device: /dev/ttyUSB0
tuya: !include third_party/tuya.yaml
xiaomi_aqara: !include third_party/xiaomi.yaml
vacuum: !include vacuum.yaml

# input (bool, number…)
binary_sensor: !include_dir_merge_list binary_sensor
input_boolean: !include_dir_merge_named input_boolean
input_number: !include_dir_merge_named input_number
input_select: !include_dir_merge_named input_select

#########################################################
