#########################################################

- platform: ping
  hosts:
    ip_phone_fr: !secret ip_phone_fr
    ip_phone_ge: !secret ip_phone_ge

#########################################################
