#########################################################
# Device tracker: ping                                  #
#########################################################

- platform: ping
  hosts:
    francois_phone_ip: !secret francois_phone_ip
    geraldine_phone_ip: !secret geraldine_phone_ip

#########################################################
# End                                                   #
#########################################################
