- platform: mqtt
  name: "Bedroom1"
  state_topic: "stat/bedroom1-light/POWER"
  command_topic: "cmnd/bedroom1-light/POWER"
  availability_topic: "tele/bedroom1-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Bedroom2"
  state_topic: "stat/bedroom2-light/POWER"
  command_topic: "cmnd/bedroom2-light/POWER"
  availability_topic: "tele/bedroom2-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Kitchen"
  state_topic: "stat/kitchen-light/POWER"
  command_topic: "cmnd/kitchen-light/POWER"
  availability_topic: "tele/kitchen-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Office"
  state_topic: "stat/office-light/POWER"
  command_topic: "cmnd/office-light/POWER"
  availability_topic: "tele/office-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Led TV"
  state_topic: "stat/tv-led/POWER"
  command_topic: "cmnd/tv-led/POWER"
  availability_topic: "tele/tv-led/LWT"
  rgb_state_topic: "stat/tv-led/color"
  rgb_command_topic: "cmnd/tv-led/color"
  brightness_state_topic: "stat/tv-led/dimmer"
  brightness_command_topic: "cmnd/tv-led/dimmer"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Led Mirror"
  state_topic: "stat/mirror-led/POWER"
  command_topic: "cmnd/mirror-led/POWER"
  availability_topic: "tele/mirror-led/LWT"
  rgb_state_topic: "stat/mirror-led/color"
  rgb_command_topic: "cmnd/mirror-led/color"
  brightness_state_topic: "stat/mirror-led/dimmer"
  brightness_command_topic: "cmnd/mirror-led/dimmer"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Living Room"
  state_topic: "stat/livingroom-light/POWER"
  command_topic: "cmnd/livingroom-light/POWER"
  availability_topic: "tele/livingroom-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
