- platform: mqtt
  name: "Led TV"
  state_topic: "stat/tv-led/POWER"
  command_topic: "cmnd/tv-led/POWER"
  availability_topic: "tele/tv-led/LWT"
  rgb_state_topic: "stat/tv-led/color"
  rgb_command_topic: "cmnd/tv-led/color"
  brightness_state_topic: "stat/tv-led/dimmer"
  brightness_command_topic: "cmnd/tv-led/dimmer"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Led Mirror"
  state_topic: "stat/mirror-led/POWER"
  command_topic: "cmnd/mirror-led/POWER"
  availability_topic: "tele/mirror-led/LWT"
  rgb_state_topic: "stat/mirror-led/color"
  rgb_command_topic: "cmnd/mirror-led/color"
  brightness_state_topic: "stat/mirror-led/dimmer"
  brightness_command_topic: "cmnd/mirror-led/dimmer"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Living Room"
  state_topic: "stat/livingroom-light/POWER"
  command_topic: "cmnd/livingroom-light/POWER"
  availability_topic: "tele/livingroom-light/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bedroom François"
  state_topic: "stat/bedlight-francois/POWER"
  command_topic: "cmnd/bedlight-francois/POWER"
  availability_topic: "tele/bedlight-francois/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bedroom Geraldine"
  state_topic: "stat/bedlight-geraldine/POWER"
  command_topic: "cmnd/bedlight-geraldine/POWER"
  availability_topic: "tele/bedlight-geraldine/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: mqtt
  name: "Bedlight"
  state_topic: "stat/bedlight/POWER"
  command_topic: "cmnd/bedlight/POWER"
  availability_topic: "tele/bedlight/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
