#########################################################

- platform: mpd
  host: !secret mpd_nas_host
  port: !secret mpd_nas_port
  name: nas

#########################################################

- platform: mpd
  host: !secret mpd_tatooine_host
  port: !secret mpd_tatooine_port
  name: tatooine

#########################################################

- platform: snapcast
  host: !secret mpd_nas_host

#########################################################

- platform: onkyo
  host: !secret onkyo_host
  sources:
    video2: 'Freebox'
    tv: 'TV'
    phono: 'Vinyle'
    bluetooth: 'Bluetooth'
    net: 'Net'

#########################################################
