#########################################################

- platform: pushbullet
  name: pushbullet
  api_key: !secret pushbullet_api

#########################################################

- platform: slack
  name: slack
  api_key: !secret slack_api
  default_channel: !secret slack_channel
  user: home-assistant
  icon: home-assistant

#########################################################
