#########################################################
# Sensor: moon                                          #
#########################################################

- platform: moon

#########################################################
# Sensor: time                                          #
#########################################################

- platform: time_date
  display_options:
    - 'time'

#########################################################
# Sensor: Average house humidity                        #
#########################################################

- platform: min_max
  name: Average house humidity
  type: mean
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################
# Sensor: Average house temperature                     #
#########################################################

- platform: min_max
  name: Average house temperature
  type: mean
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################
# Sensor: Max humidity in house                         #
#########################################################

- platform: min_max
  name: Max humidity in house
  type: max
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################
# Sensor: Max temperature in house                      #
#########################################################

- platform: min_max
  name: Max temperature in home
  type: max
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################
# Sensor: History living room light                     #
#########################################################

- platform: history_stats
  name: "historique lumière salon"
  entity_id: switch.0220052668c63aac1fc7
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################
# Sensor: History coffee machine power supply           #
#########################################################

- platform: history_stats
  name: "historique alimentation cafetière"
  entity_id: switch.002009152c3ae81bacf6
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################
# Sensor: History freebox tv power supply               #
#########################################################

- platform: history_stats
  name: "historique alimentation freebox mini 4k"
  entity_id: switch.03200172dc4f22245507
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################
# Sensor: template                                      #
#########################################################

- platform: template
  sensors:

    alarm_clock_hour:
      value_template: "{{ states.input_number.alarm_clock_hour.state | int }}"

    alarm_clock_minute:
      value_template: "{{ states.input_number.alarm_clock_minute.state | int }}"

    alarm_clock_time:
      value_template: "{{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    alarm_clock_time_long:
      value_template: "{% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    temp_sensor_chambre_1:
      friendly_name: "batterie capteur température chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044b4d7d', 'battery_level') }}"

    bouton_chambre_1:
      friendly_name: "batterie bouton chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033e8984', 'battery_level') }}"

    window_chambre_1:
      friendly_name: "batterie fenêtre chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f41fe9', 'battery_level') }}"

    temp_sensor_chambre_2:
      friendly_name: "batterie capteur température chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00036b45e1', 'battery_level') }}"

    bouton_chambre_2:
      friendly_name: "batterie bouton chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033ef6d8', 'battery_level') }}"

    cube_chambre_2:
      friendly_name: "batterie cube chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.cube_158d00029b46d6', 'battery_level') }}"

    window_chambre_2:
      friendly_name: "batterie fenêtre chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4baa8', 'battery_level') }}"

    temp_sensor_bathroom:
      friendly_name: "batterie capteur température salle de bain"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044592d5', 'battery_level') }}"

    temp_sensor_shower_room:
      friendly_name: "batterie capteur température salle d'eau"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d0004102ae1', 'battery_level') }}"

    temp_sensor_living_room:
      friendly_name: "batterie capteur température salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044acc21', 'battery_level') }}"

    window_living_room:
      friendly_name: "batterie fenêtre salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d00039fe3a9', 'battery_level') }}"

    bouton_cuisine:
      friendly_name: "batterie bouton cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00035a995a', 'battery_level') }}"

    temp_sensor_kitchen:
      friendly_name: "batterie capteur température cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00033b0bd7', 'battery_level') }}"

    window_kitchen:
      friendly_name: "batterie fenêtre salle à manger"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003a0f809', 'battery_level') }}"

    door_entrance:
      friendly_name: "batterie porte d'entrée"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4ba8d', 'battery_level') }}"

#########################################################
# End                                                   #
#########################################################
