#########################################################

- platform: moon

#########################################################

- platform: time_date
  display_options:
    - 'time'

#########################################################

- platform: min_max
  name: average home humidity
  type: mean
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################

- platform: min_max
  name: max home humidity
  type: max
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################

- platform: min_max
  name: average home temperature
  type: mean
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################

- platform: min_max
  name: max home temperature
  type: max
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################

- platform: min_max
  name: average home illumination
  type: mean
  entity_ids:
    - sensor.illumination_04cf8cb87b01
    - sensor.illumination_158d0003f3cd60
    - sensor.illumination_158d0003faef01
    - sensor.illumination_158d00044993aa
    - sensor.illumination_158d00044c67d5
    - sensor.illumination_158d00044d007b

#########################################################

- platform: min_max
  name: max home illumination
  type: max
  entity_ids:
    - sensor.illumination_04cf8cb87b01
    - sensor.illumination_158d0003f3cd60
    - sensor.illumination_158d0003faef01
    - sensor.illumination_158d00044993aa
    - sensor.illumination_158d00044c67d5
    - sensor.illumination_158d00044d007b

#########################################################

- platform: history_stats
  name: "historique lumière salon"
  entity_id: switch.0220052668c63aac1fc7
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique alimentation cafetière"
  entity_id: switch.002009152c3ae81bacf6
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique alimentation freebox mini 4k"
  entity_id: switch.03200172dc4f22245507
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique alimentation tv"
  entity_id: switch.64680137bcddc2542a40
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lave linge"
  entity_id: input_boolean.washing_machine
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: template
  sensors:

    alarm_clock_hour:
      value_template: "{{ states.input_number.alarm_clock_hour.state | int }}"

    alarm_clock_minute:
      value_template: "{{ states.input_number.alarm_clock_minute.state | int }}"

    alarm_clock_time:
      value_template: "{{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    alarm_clock_time_long:
      value_template: "{% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    temp_sensor_chambre_1:
      friendly_name: "batterie capteur température chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044b4d7d', 'battery_level') }}"

    bouton_chambre_1:
      friendly_name: "batterie bouton chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033e8984', 'battery_level') }}"

    window_chambre_1:
      friendly_name: "batterie fenêtre chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f41fe9', 'battery_level') }}"

    temp_sensor_chambre_2:
      friendly_name: "batterie capteur température chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00036b45e1', 'battery_level') }}"

    bouton_chambre_2:
      friendly_name: "batterie bouton chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033ef6d8', 'battery_level') }}"

    cube_chambre_2:
      friendly_name: "batterie cube chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.cube_158d00029b46d6', 'battery_level') }}"

    window_chambre_2:
      friendly_name: "batterie fenêtre chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4baa8', 'battery_level') }}"

    temp_sensor_bathroom:
      friendly_name: "batterie capteur température salle de bain"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044592d5', 'battery_level') }}"

    temp_sensor_shower_room:
      friendly_name: "batterie capteur température salle d'eau"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d0004102ae1', 'battery_level') }}"

    temp_sensor_living_room:
      friendly_name: "batterie capteur température salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044acc21', 'battery_level') }}"

    window_living_room:
      friendly_name: "batterie fenêtre salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d00039fe3a9', 'battery_level') }}"

    bouton_cuisine:
      friendly_name: "batterie bouton cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00035a995a', 'battery_level') }}"

    temp_sensor_kitchen:
      friendly_name: "batterie capteur température cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00033b0bd7', 'battery_level') }}"

    window_kitchen:
      friendly_name: "batterie fenêtre salle à manger"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003a0f809', 'battery_level') }}"

    door_entrance:
      friendly_name: "batterie porte d'entrée"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4ba8d', 'battery_level') }}"

    last_open_door_entrance:
      friendly_name: "Dernière ouverture porte d'entrée"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003f4ba8d.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_entrance:
      friendly_name: "Dernier mouvement détecté dans l'entrée"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044993aa.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_living_room:
      friendly_name: "Dernier mouvement détecté dans le salon"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044d007b.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_kitchen:
      friendly_name: "Dernier mouvement détecté dans la cuisine"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044c67d5.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_bedroom_2:
      friendly_name: "Dernier mouvement détecté dans la chambre 2"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d0003faef01.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_office:
      friendly_name: "Dernier mouvement détecté dans le bureau"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d0003f3cd60.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_washing_machine:
      friendly_name: "Derniere action machine a lavée"
      value_template: '{{ as_timestamp(states.input_boolean.washing_machine.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

#########################################################
