#########################################################

- platform: moon

#########################################################

- platform: time_date
  display_options:
    - 'time'

#########################################################

- platform: min_max
  name: average home humidity
  type: mean
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################

- platform: min_max
  name: max home humidity
  type: max
  entity_ids:
    - sensor.humidity_158d00033b0bd7
    - sensor.humidity_158d00036b45e1
    - sensor.humidity_158d0004102ae1
    - sensor.humidity_158d00044592d5
    - sensor.humidity_158d00044acc21
    - sensor.humidity_158d00044b4d7d

#########################################################

- platform: min_max
  name: average home temperature
  type: mean
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################

- platform: min_max
  name: max home temperature
  type: max
  entity_ids:
    - sensor.temperature_158d00033b0bd7
    - sensor.temperature_158d00036b45e1
    - sensor.temperature_158d0004102ae1
    - sensor.temperature_158d00044592d5
    - sensor.temperature_158d00044acc21
    - sensor.temperature_158d00044b4d7d

#########################################################

- platform: history_stats
  name: "historique fenêtre salon"
  entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique fenêtre cuisine"
  entity_id: binary_sensor.door_window_sensor_158d0003a0f809
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique fenêtre chambre 1"
  entity_id: binary_sensor.door_window_sensor_158d0003f41fe9
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique fenêtre chambre 2"
  entity_id: binary_sensor.door_window_sensor_158d0003f4baa8
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière salon"
  entity_id: light.living_room
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière évier"
  entity_id: switch.wall_switch_left_158d00045fab25
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière cuisine"
  entity_id: switch.wall_switch_right_158d00045fab25
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière salle d'eau"
  entity_id: switch.wall_switch_158d000357da1a
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière chambre 1"
  entity_id: light.bedroom1
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière chambre 2"
  entity_id: light.bedroom2
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière salle de bain (plafond)"
  entity_id: switch.wall_switch_right_158d00039d4efd
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lumière salle de bain (mirroir)"
  entity_id: switch.wall_switch_left_158d00039d4efd
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique alimentation cafetière"
  entity_id: switch.coffee_socket
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique alimentation tv"
  entity_id: switch.sonoff_1000a12e98
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lave linge"
  entity_id: input_boolean.washing_machine
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: history_stats
  name: "historique lave vaisselle"
  entity_id: input_boolean.dishwasher
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

#########################################################

- platform: template
  sensors:

    alarm_clock_hour:
      value_template: "{{ states.input_number.alarm_clock_hour.state | int }}"

    alarm_clock_minute:
      value_template: "{{ states.input_number.alarm_clock_minute.state | int }}"

    alarm_clock_time:
      value_template: "{{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    alarm_clock_time_long:
      value_template: "{% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}"

    temp_sensor_chambre_1:
      friendly_name: "batterie capteur température chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044b4d7d', 'battery_level') }}"

    bouton_chambre_1:
      friendly_name: "batterie bouton chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033e8984', 'battery_level') }}"

    window_chambre_1:
      friendly_name: "batterie fenêtre chambre 1"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f41fe9', 'battery_level') }}"

    temp_sensor_chambre_2:
      friendly_name: "batterie capteur température chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00036b45e1', 'battery_level') }}"

    bouton_chambre_2:
      friendly_name: "batterie bouton chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00033ef6d8', 'battery_level') }}"

    cube_chambre_2:
      friendly_name: "batterie cube chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.cube_158d00029b46d6', 'battery_level') }}"

    window_chambre_2:
      friendly_name: "batterie fenêtre chambre 2"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4baa8', 'battery_level') }}"

    temp_sensor_bathroom:
      friendly_name: "batterie capteur température salle de bain"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044592d5', 'battery_level') }}"

    temp_sensor_shower_room:
      friendly_name: "batterie capteur température salle d'eau"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d0004102ae1', 'battery_level') }}"

    temp_sensor_living_room:
      friendly_name: "batterie capteur température salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00044acc21', 'battery_level') }}"

    window_living_room:
      friendly_name: "batterie fenêtre salon"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d00039fe3a9', 'battery_level') }}"

    bouton_cuisine:
      friendly_name: "batterie bouton cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.switch_158d00035a995a', 'battery_level') }}"

    temp_sensor_kitchen:
      friendly_name: "batterie capteur température cuisine"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.temperature_158d00033b0bd7', 'battery_level') }}"

    window_kitchen:
      friendly_name: "batterie fenêtre salle à manger"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003a0f809', 'battery_level') }}"

    door_entrance:
      friendly_name: "batterie porte d'entrée"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.door_window_sensor_158d0003f4ba8d', 'battery_level') }}"

    last_open_door_entrance:
      friendly_name: "Dernière ouverture porte d'entrée"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003f4ba8d.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_entrance:
      friendly_name: "Dernier mouvement détecté dans l'entrée"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044993aa.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_living_room:
      friendly_name: "Dernier mouvement détecté dans le salon"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044d007b.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_kitchen:
      friendly_name: "Dernier mouvement détecté dans la cuisine"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d00044c67d5.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_bedroom_2:
      friendly_name: "Dernier mouvement détecté dans la chambre 2"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d0003faef01.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_movement_in_office:
      friendly_name: "Dernier mouvement détecté dans le bureau"
      value_template: '{{ as_timestamp(states.binary_sensor.motion_sensor_158d0003f3cd60.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_washing_machine:
      friendly_name: "Derniere action lave linge"
      value_template: '{{ as_timestamp(states.input_boolean.washing_machine.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_dishwasher:
      friendly_name: "Derniere action lave vaisselle"
      value_template: '{{ as_timestamp(states.input_boolean.dishwasher.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_window_living_room:
      friendly_name: "Dernière action fenêtre salon"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d00039fe3a9.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_window_kitchen:
      friendly_name: "Dernière action fenêtre salle à manger"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003a0f809.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_window_bedroom_1:
      friendly_name: "Dernière action fenetre chambre 1"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003f41fe9.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_window_bedroom_2:
      friendly_name: "Dernière action fenetre chambre 2"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003f4baa8.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    last_action_door_entrance:
      friendly_name: "Dernière action porte d'entrée"
      value_template: '{{ as_timestamp(states.binary_sensor.door_window_sensor_158d0003f4ba8d.last_updated) | timestamp_custom("%d/%m/%y %H:%M", true) }}'

    history_light_living_room:
      friendly_name: "Utilisation lumière salon aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_salon.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_kitchen:
      friendly_name: "Utilisation lumière cuisine aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_cuisine.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_kitchen_sink:
      friendly_name: "Utilisation lumière cuisine (évier) aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_evier.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_shower_room:
      friendly_name: "Utilisation lumière salle d'eau aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_salle_d_eau.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_bedroom_1:
      friendly_name: "Utilisation lumière chambre 1 aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_chambre_1.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_bedroom_2:
      friendly_name: "Utilisation lumière chambre 2 aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_chambre_2.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_bathroom_top:
      friendly_name: "Utilisation lumière salle de bain (plafond) aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_salle_de_bain_plafond.attributes.value }}'
      icon_template: 'mdi:clock'

    history_light_bathroom_mirror:
      friendly_name: "Utilisation lumière salle de bain (mirroir) aujourd'hui"
      value_template: '{{ states.sensor.historique_lumiere_salle_de_bain_mirroir.attributes.value }}'
      icon_template: 'mdi:clock'

    history_dishwasher:
      friendly_name: "Utilisation du lave vaisselle aujourd'hui"
      value_template: '{{ states.sensor.historique_lave_vaisselle.attributes.value }}'
      icon_template: 'mdi:clock'

    history_washing_machine:
      friendly_name: "Utilisation du lave linge aujourd'hui"
      value_template: '{{ states.sensor.historique_lave_linge.attributes.value }}'
      icon_template: 'mdi:clock'

    onkyo_volume:
      friendly_name: "Volume Ampli"
      value_template: '{{ states.media_player.onkyo_receiver.attributes.volume_level }}'

    onkyo_muted:
      friendly_name: "Ampli volume mute"
      value_template: '{{ states.media_player.onkyo_receiver.attributes.is_volume_muted }}'

    onkyo_source:
      friendly_name: "Ampli source"
      value_template: '{{ states.media_player.onkyo_receiver.attributes.source }}'

    sun_elevation:
      friendly_name: "Élévation du soleil"
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

    battery_fr_phone:
      friendly_name: "Batterie Téléphone Fr"
      unit_of_measurement: '%'
      value_template: "{{ state_attr('device_tracker.moto_g_7_2', 'battery_level')|round }}"
      device_class: battery

#########################################################

- platform: waze_travel_time
  name: "Trajet Maison-Travail"
  origin: zone.Home
  destination: zone.Work
  region: 'EU'
  realtime: true
  units: 'metric'
  vehicle_type: 'car'

#########################################################
