- platform: template
  switches:
    cover_state_salon_bas:
      friendly_name: "volet salon (bas)"
      value_template: "{% if is_state('input_boolean.cover_salon_bas', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_cover
        data:
          cover_entity_id: cover.salon_bas
          input_boolean_entity_id: input_boolean.cover_salon_bas
      turn_off:
        service: script.close_cover
        data:
          cover_entity_id: cover.salon_bas
          input_boolean_entity_id: input_boolean.cover_salon_bas
      icon_template: >-
          {% if is_state('input_boolean.cover_salon_bas', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_salon_haut:
      friendly_name: "volet salon (haut)"
      value_template: "{% if is_state('input_boolean.cover_salon_haut', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_cover
        data:
          cover_entity_id: cover.salon_haut
          input_boolean_entity_id: input_boolean.cover_salon_haut
      turn_off:
        service: script.close_cover
        data:
          cover_entity_id: cover.salon_haut
          input_boolean_entity_id: input_boolean.cover_salon_haut
      icon_template: >-
          {% if is_state('input_boolean.cover_salon_haut', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_cuisine:
      friendly_name: "volet cuisine"
      value_template: "{% if is_state('input_boolean.cover_cuisine', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_cover
        data:
          cover_entity_id: cover.cuisine
          input_boolean_entity_id: input_boolean.cover_cuisine
      turn_off:
        service: script.close_cover
        data:
          cover_entity_id: cover.cuisine
          input_boolean_entity_id: input_boolean.cover_cuisine
      icon_template: >-
          {% if is_state('input_boolean.cover_cuisine', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}
    
    cover_state_chambre_1:
      friendly_name: "volet chambre 1"
      value_template: "{% if is_state('input_boolean.cover_chambre_1', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_cover
        data:
          cover_entity_id: cover.chambre_1
          input_boolean_entity_id: input_boolean.cover_chambre_1
      turn_off:
        service: script.close_cover
        data:
          cover_entity_id: cover.chambre_1
          input_boolean_entity_id: input_boolean.cover_chambre_1
      icon_template: >-
          {% if is_state('input_boolean.cover_chambre_1', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}
    
    cover_state_chambre_2:
      friendly_name: "volet chambre 2"
      value_template: "{% if is_state('input_boolean.cover_chambre_2', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_cover
        data:
          cover_entity_id: cover.chambre_2
          input_boolean_entity_id: input_boolean.cover_chambre_2
      turn_off:
        service: script.close_cover
        data:
          cover_entity_id: cover.chambre_2
          input_boolean_entity_id: input_boolean.cover_chambre_2
      icon_template: >-
          {% if is_state('input_boolean.cover_chambre_2', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}
