#########################################################

- platform: broadlink
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  type: !secret broadlink_type

#########################################################

- platform: template
  switches:
    cover_state_salon_bas:
      friendly_name: "volet salon (bas)"
      value_template: "{% if is_state('input_boolean.cover_salon_bas', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.salon_bas
          input_boolean_entity_id: input_boolean.cover_salon_bas
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.salon_bas
          input_boolean_entity_id: input_boolean.cover_salon_bas
      icon_template: >-
          {% if is_state('input_boolean.cover_salon_bas', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_salon_haut:
      friendly_name: "volet salon (haut)"
      value_template: "{% if is_state('input_boolean.cover_salon_haut', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.salon_haut
          input_boolean_entity_id: input_boolean.cover_salon_haut
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.salon_haut
          input_boolean_entity_id: input_boolean.cover_salon_haut
      icon_template: >-
          {% if is_state('input_boolean.cover_salon_haut', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_cuisine:
      friendly_name: "volet cuisine"
      value_template: "{% if is_state('input_boolean.cover_cuisine', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.cuisine
          input_boolean_entity_id: input_boolean.cover_cuisine
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.cuisine
          input_boolean_entity_id: input_boolean.cover_cuisine
      icon_template: >-
          {% if is_state('input_boolean.cover_cuisine', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_chambre_1:
      friendly_name: "volet chambre 1"
      value_template: "{% if is_state('input_boolean.cover_chambre_1', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.chambre_1
          input_boolean_entity_id: input_boolean.cover_chambre_1
      turn_off:
        service: script.close_bedroom_shutter
        data:
          cover_entity_id: cover.chambre_1
          input_boolean_entity_id: input_boolean.cover_chambre_1
      icon_template: >-
          {% if is_state('input_boolean.cover_chambre_1', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_chambre_2:
      friendly_name: "volet chambre 2"
      value_template: "{% if is_state('input_boolean.cover_chambre_2', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.chambre_2
          input_boolean_entity_id: input_boolean.cover_chambre_2
      turn_off:
        service: script.close_bedroom_shutter
        data:
          cover_entity_id: cover.chambre_2
          input_boolean_entity_id: input_boolean.cover_chambre_2
      icon_template: >-
          {% if is_state('input_boolean.cover_chambre_2', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

#########################################################

- platform: mqtt
  name: "Coffee Socket"
  state_topic: "stat/coffee-socket/POWER"
  command_topic: "cmnd/coffee-socket/POWER"
  availability_topic: "tele/coffee-socket/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Camera Socket"
  state_topic: "stat/camera-socket/POWER"
  command_topic: "cmnd/camera-socket/POWER"
  availability_topic: "tele/camera-socket/LWT"
  qos: 1
  optimistic: false
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Outdoor Socket #1"
  state_topic: "stat/outdoor-socket/POWER1"
  command_topic: "cmnd/outdoor-socket/POWER1"
  qos: 1
  optimistic: false
  retain: true
- platform: mqtt
  name: "Outdoor Socket #2"
  state_topic: "stat/outdoor-socket/POWER2"
  command_topic: "cmnd/outdoor-socket/POWER2"
  qos: 1
  optimistic: false
  retain: true
