- alias: "Change ampli source to freebox"
  trigger:
    - platform: state
      entity_id: input_select.ampli_sources
      to: 'freebox'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.onkyo_receiver
        source: 'video2'
