- alias: "Change ampli source to tv"
  trigger:
    - platform: state
      entity_id: input_select.ampli_sources
      to: 'tv'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.onkyo_receiver
        source: 'tv'
