- alias: Nobody is in the living room
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044d007b
      to: 'off'
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.sonoff_1000a12e98
        state: 'off'
      - condition: state
        entity_id: binary_sensor.ping_tv
        state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00045fabbe
