- alias: Nobody is in the living room
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_mirror
      to: 'off'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.living_room_motion_tv
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.tv_socket
        state: 'off'
      - condition: state
        entity_id: binary_sensor.ping_tv
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.living_room_light_and_leds
