- alias: "living room switch on/off the light from the living_room button"
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d00045fabbe
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_left_158d00045fabbe
      to: 'off'
  action:
    - service: light.toggle
      entity_id: light.living_room
