- alias: "Ampli still up be and no one listen"
  trigger:
    - platform: state
      entity_id: media_player.onkyo_receiver
      to: 'on'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.tv_socket
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: sensor.onkyo_source
          state: 'TV'
        - condition: state
          entity_id: sensor.onkyo_source
          state: 'Freebox'
  action:
    - service: switch.turn_off
      entity_id: switch.ampli
