- alias: "living room window is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_door
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_living_room
