- alias: "living room window is now closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_door
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_living_room
