- alias: "living room window is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_living_room
    - service: notify.slack
      data:
        message: "The window in living room is open"
