- alias: "living room window timer is over"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.window_living_room
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "Now you can close the window in living room"
