#########################################################

- alias: switch on the stairs from the entrance button
  trigger:
    platform: state
    entity_id: switch.wall_switch_right_158d00045f9e86
    to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d00045f9f36

#########################################################

- alias: switch off the stairs from the entrance button
  trigger:
    platform: state
    entity_id: switch.wall_switch_right_158d00045f9e86
    to: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d00045f9f36

#########################################################

- alias: turn off the stairs after 3mn
  trigger:
    - platform: state
      entity_id: switch.wall_switch_right_158d00045f9f36
      to: 'on'
      for:
        minutes: 3
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00045f9f36

#########################################################
