- alias: "turn off the stairs after 2mn"
  trigger:
    - platform: state
      entity_id: switch.stairs_light
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.mode_canicule
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.stairs_light
