- alias: "switch on/off the stairs from the entrance button"
  trigger:
    - platform: state
      entity_id: switch.wall_switch_right_158d00045f9e86
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_right_158d00045f9e86
      to: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d00045f9f36
