#########################################################

- alias: "Button kitchen - one click: toggle light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00035a995a
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.0220052668c63aac1fc7

#########################################################

#- alias: "Button kitchen - long press: toggle ground floor shutters"
#  trigger:
#    - platform: event
#      event_type: xiaomi_aqara.click
#      event_data:
#        entity_id: binary_sensor.switch_158d00035a995a
#        click_type: long_click_press
#  action:
#    - service: switch.toggle
#      entity_id:
#        - switch.cover_state_cuisine
#        - switch.cover_state_salon_bas
#        - switch.cover_state_salon_haut

#########################################################

- alias: "Button kitchen - double click: toggle kitchen's shutters"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00035a995a
        click_type: double
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_cuisine

#########################################################
