#########################################################

- alias: Someone is in the kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044c67d5
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 3 }}'
      - condition: state
        entity_id: switch.cover_state_kitchen
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d00045fab25

#########################################################

- alias: Nobody is in the kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044c67d5
      to: 'off'
      for:
        minutes: 3
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00045fab25

#########################################################
