#########################################################

- alias: Someone is in the kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044c67d5
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 2 }}'
      - condition: state
        entity_id: switch.cover_state_cuisine
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.50052752dc4f22e16c99

#########################################################

- alias: Nobody is in the kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044c67d5
      to: 'off'
      for:
        minutes: 3 # 2 mn from detection = 5mn on
  action:
    - service: switch.turn_off
      entity_id: switch.50052752dc4f22e16c99

#########################################################

- alias: Someone switch off the kitchen light
  trigger:
    - platform: state
      entity_id: switch.50052752dc4f22e16c99
      to: 'unavailable'
  action:
    - service: notify.slack
      data_template:
        title: "Home-Assistant Light off"
        message: "@channel someone switch off the kitchen light please turn on again. {{ trigger.to_state.attributes.friendly_name }}"

#########################################################
