#########################################################

- alias: "bedroom 2 - one click: switch on light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: single
  action:
    - service: light.toggle
      entity_id: light.bedroom2

#########################################################

- alias: "bedroom 2 - double click: switch off light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: double
  action:
    - service: light.toggle
      entity_id: light.bedroom2

#########################################################

- alias: "bedroom 2 - long press: toggle shutters"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_chambre_2

#########################################################
