#########################################################

- alias: Someone is in the bedroom 2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '04:00:00'
        after: '16:00:00'
      - condition: state
        entity_id: input_select.house_mode
        state: 'home'
      - condition: state
        entity_id: switch.cover_state_bedroom_2
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_158d00044f52ec

#########################################################

- alias: Nobody is in the bedroom 2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'off'
      for:
        minutes: 3
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f52ec

#########################################################
