#########################################################

- alias: Someone is in the bedroom 2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '04:00:00'
        after: '16:00:00'
      - condition: state
        entity_id: input_select.house_mode
        state: 'Home'
      - condition: state
        entity_id: switch.cover_state_chambre_2
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bedroom2

#########################################################

- alias: Nobody is in the bedroom 2
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'off'
      for:
        minutes: 3 # 2 mn from detection = 5mn on
  action:
    - service: light.turn_off
      entity_id: light.bedroom2

#########################################################

- alias: Someone switch off the bedroom light
  trigger:
    - platform: state
      entity_id: light.bedroom2
      to: 'unavailable'
  action:
    - service: notify.slack
      data_template:
        title: "Home-Assistant Light off"
        message: "@channel someone switch off the bedroom 2 light please turn on again. {{ trigger.to_state.attributes.friendly_name }}"

#########################################################
