- alias: "Someone is in the entrance"
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.cover_state_mezzanine
      state: 'off'
    - condition: state
      entity_id: switch.cover_state_living_room
      state: 'off'
    - condition: state
      entity_id: switch.tv_socket
      state: 'off'
    - condition: state
      entity_id: binary_sensor.ping_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.mode_canicule
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.entrance_light
