- alias: "Nobody is in the entrance"
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion
      to: 'off'
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      entity_id: switch.entrance_light
