- alias: Fr & Ge are not at home set mode 'away'
  trigger:
    - platform: state
      entity_id: device_tracker.ip_phone_fr
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.ip_phone_ge
      to: 'not_home'
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: 'home'
      - condition: state
        entity_id: device_tracker.ip_phone_ge
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.ip_phone_fr
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.francois_moto_g7 #geoip fr
        state: 'not_home'
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'away'
