- alias: "Someone is present in the office"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_desk_francois
      to: 'on'
    - platform: state
      entity_id: binary_sensor.office_motion_desk_geraldine
      to: 'on'
    - platform: state
      entity_id: binary_sensor.office_motion_wall
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: 'home'
      - condition: state
        entity_id: switch.cover_state_mezzanine
        state: 'off'
      - condition: state
        entity_id: input_boolean.mode_canicule
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.office_light
