- alias: Blink at 23h00 and 23h10 sunday to thursday
  trigger:
    - platform: time
      at: '23:00:00'
    - platform: time
      at: '23:10:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - sun
      - condition: state
        entity_id: switch.wall_switch_158d00044f0b9b
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f0b9b
    - service: switch.turn_on
      entity_id: switch.wall_switch_158d00044f0b9b
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f0b9b
    - service: switch.turn_on
      entity_id: switch.wall_switch_158d00044f0b9b
