- alias: "Light on luminosity low"
  trigger:
    - platform: template
      value_template: "{% if states('sensor.office_lumi_sensor_illuminance')|int <= 12 %}true{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: 'home'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.office_motion_desk_francois
          state: 'on'
        - condition: state
          entity_id: binary_sensor.office_motion_desk_geraldine
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.office_light
