- alias: "Switch off socket on night mode"
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'night'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.02063503600194face36_1
        - switch.02063503600194face36_2
        - switch.02063503600194face36_3
        - switch.02063503600194face36_4
    - service: switch.turn_on
      entity_id:
        - switch.02063503600194face36_5
