#########################################################

- platform: template
  switches:
    cover_state_living_room:
      friendly_name: "volet salon"
      value_template: "{% if is_state('input_boolean.cover_living_room', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.living_room
          input_boolean_entity_id: input_boolean.cover_living_room
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.living_room
          input_boolean_entity_id: input_boolean.cover_living_room
      icon_template: >-
          {% if is_state('input_boolean.cover_living_room', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_mezzanine:
      friendly_name: "volet mezzanine"
      value_template: "{% if is_state('input_boolean.cover_mezzanine', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.mezzanine
          input_boolean_entity_id: input_boolean.cover_mezzanine
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.mezzanine
          input_boolean_entity_id: input_boolean.cover_mezzanine
      icon_template: >-
          {% if is_state('input_boolean.cover_mezzanine', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_kitchen:
      friendly_name: "volet cuisine"
      value_template: "{% if is_state('input_boolean.cover_kitchen', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.kitchen
          input_boolean_entity_id: input_boolean.cover_kitchen
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.kitchen
          input_boolean_entity_id: input_boolean.cover_kitchen
      icon_template: >-
          {% if is_state('input_boolean.cover_kitchen', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_bedroom_1:
      friendly_name: "volet chambre 1"
      value_template: "{% if is_state('input_boolean.cover_bedroom_1', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.bedroom_1
          input_boolean_entity_id: input_boolean.cover_bedroom_1
      turn_off:
        service: script.close_shutter
        data:
          cover_entity_id: cover.bedroom_1
          input_boolean_entity_id: input_boolean.cover_bedroom_1
      icon_template: >-
          {% if is_state('input_boolean.cover_bedroom_1', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    cover_state_bedroom_2:
      friendly_name: "volet chambre 2"
      value_template: "{% if is_state('input_boolean.cover_bedroom_2', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: script.open_shutter
        data:
          cover_entity_id: cover.bedroom_2
          input_boolean_entity_id: input_boolean.cover_bedroom_2
      turn_off:
        service: script.close_bedroom_shutter
        data:
          cover_entity_id: cover.bedroom_2
          input_boolean_entity_id: input_boolean.cover_bedroom_2
      icon_template: >-
          {% if is_state('input_boolean.cover_bedroom_2', 'on') %}
            mdi:window-shutter-open
          {% else %}
            mdi:window-shutter
          {% endif %}

    remote_tv_power:
      friendly_name: "tv power"
      value_template: "{% if is_state('binary_sensor.ping_tv', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.tv
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.tv

    remote_ampli_power:
      friendly_name: "ampli power"
      value_template: "{% if is_state('binary_sensor.ping_ampli', 'on') %}True{% else %}False{% endif %}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.ampli
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.ampli

#########################################################
