- alias: "switch on/off the cover with long press on button"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_bedroom_2
