- alias: "Bedroom 2 cube move, rotate or tap twice only when vacuum_up is docked put house_mode night"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: move
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: rotate
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: tap_twice
  condition:
    - condition: state
      entity_id: vacuum.vacuum_up
      state: 'docked'
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Night'
