- alias: "button single or double click switch on/off light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033ef6d8
        click_type: double
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_158d00044f52ec
