- alias: "nobody present in bedroom 2 since 3mn"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.0x00158d000466764e_occupancy
      to: 'on'
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f52ec
