- alias: "nobody present in bedroom 2 since 3mn"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003faef01
      to: 'off'
      for:
        minutes: 3
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f52ec
