- alias: "bedroom 2 window is close"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003f4baa8
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_bedroom2
    - service: notify.slack
      data:
        message: "The window in bedroom 2 is now closed"
