- alias: "If we close living room window during 3mn after the sunset we close the cover"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_living_room

- alias: "Switch on outdoor lights at 20h"
  trigger:
    - platform: time
      at: "19:59:30"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.outdoor_socket_1
