- alias: "If we close living room window during 3mn after the sunset we close the cover and switch off light"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_living_room
    - service: switch.turn_off
      entity_id:
        - switch.outdoor_socket_1
        - switch.outdoor_socket_2
