- alias: "Open all shutters in ground floor at 9am (weekend)"
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    #- service: homeassistant.turn_on
    #  entity_id:
    #    - group.downstair_covers
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_kitchen
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_living_room
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_mezzanine
