- alias: "Open all shutters in ground floor at 8am (weekday)"
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    #- service: homeassistant.turn_on
    #  entity_id:
    #    - group.downstair_covers
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_kitchen
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_living_room
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_mezzanine
