- alias: "Sunset close living_room cover if window is closed"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
    - condition: and
      conditions:
      - condition: time
        after: '20:10:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
        state: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_living_room
