#########################################################

- alias: Someone is in the office
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f3cd60
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 3 }}'
      - condition: state
        entity_id: switch.cover_state_mezzanine
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_158d00044f0b9b

#########################################################

- alias: Nobody is in the office
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f3cd60
      to: 'off'
      for:
        minutes: 12
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d00044f0b9b

#########################################################
