#########################################################

- alias: Someone detect in office tv is off switch off tv
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f3cd60
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.64680137bcddc2542a40
        state: 'on'
      - condition: state
        entity_id: binary_sensor.ping_tv
        state: 'off'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.03200172dc4f22245507 # freebox
        - switch.64680137bcddc2542a40 # alimentation tv

#########################################################
