#########################################################

- alias: Someone is in the living room
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044d007b
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044993aa
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: '{{ state_attr("sun.sun", "elevation") < 3 }}'
          - condition: time
            after: '16:00:00'
            before: '04:00:00'
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.cover_state_salon_haut
            state: 'off'
          - condition: state
            entity_id: switch.cover_state_salon_bas
            state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room

#########################################################

- alias: Nobody is in the living room
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044d007b
      to: 'off'
      for:
        minutes: 10 # 2 mn from detection = 12mn on
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.sonoff_1000a12e98
        state: 'off'
      - condition: state
        entity_id: binary_sensor.ping_tv
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.living_room

#########################################################

- alias: switch on the living room from the living_room button
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d00045fabbe
    to: 'on'
  action:
    - service: light.toggle
      entity_id: light.living_room

#########################################################

- alias: switch off the living room from the living_room button
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d00045fabbe
    to: 'off'
  action:
    - service: light.toggle
      entity_id: light.living_room

#########################################################
