#########################################################

- alias: "Window living room is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_living_room
    - service: notify.slack
      data:
        message: "The window in living room is open"

#########################################################

- alias: timer finish window open
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.window_living_room
  action:
    - service: notify.slack
      data:
        message: "Now you can close the window in living room"

#########################################################

- alias: "Window living room is close"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_living_room
    - service: notify.slack
      data:
        message: "The window in living room is now closed"

#########################################################
