- alias: "bathroom turn off the mirror light after 20minutes"
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d00039d4efd
      to: 'on'
      for:
        minutes: 20
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00039d4efd
