- alias: "bathroom turn off ceiling light after 1h"
  trigger:
    - platform: state
      entity_id: switch.wall_switch_right_158d00039d4efd
      to: 'on'
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00039d4efd
