- alias: "bathroom turn off light after 1h"
  trigger:
    - platform: state
      entity_id: switch.bathroom_light
      to: 'on'
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_light
