- alias: "nobody present in bedroom 2 since 3mn"
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_motion_corner
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: binary_sensor.master_bedroom_motion_entrance
      state: 'off'
      for:
        minutes: 3
  action:
    - service: light.turn_off
      entity_id: light.bedroom_francois
    - service: light.turn_off
      entity_id: light.bedroom_geraldine
