- alias: "master bedroom window is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_window
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_master_bedroom
