- alias: timer finish window open
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.window_master_bedroom
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "Now you can close the window in the master bedroom"
