- alias: "Sunset close covers"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:15:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_kitchen
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_mezzanine
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_bedroom
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_master_bedroom
