- alias: "Sunset switch on the light if door open"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
    - condition: and
      conditions:
      - condition: time
        after: '16:00:00'
        before: '23:00:00'
      - condition: state
        entity_id: binary_sensor.living_room_door
        state: 'on'
      - condition: state
        entity_id: switch.outdoor_socket_1
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.outdoor_socket_1
