- alias: "Someone is present in the shower_room"
  trigger:
    - platform: state
      entity_id: binary_sensor.shower_room_motion_sensor
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.shower_room_light
