#########################################################

- alias: turn off the shower_room light after 2h
  trigger:
    - platform: state
      entity_id: switch.wall_switch_158d000357da1a
      to: 'on'
      for:
        hours: 2
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_158d000357da1a

#########################################################
