#########################################################

- alias: "Cube bedroom 2 - flip 90: toggle light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: flip90
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_chambre_2

#########################################################

- alias: "Cube bedroom 2 - flip 180: toggle shutters"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: flip180
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_chambre_2

#########################################################

- alias: "Cube bedroom 2 - move: toggle light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: move
  action:
    - service: switch.toggle
      entity_id: switch.50052752dc4f22e1706a

#########################################################

- alias: "Cube bedroom 2 - rotate: night mode"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: rotate
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Night'

#########################################################

- alias: "Cube bedroom 2 - tap twice: night mode"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00029b46d6
        action_type: tap_twice
  action:
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data:
        option: 'Night'

#########################################################
