- alias: 'interrupteur chambre 1 click lumiere'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033e8984
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.28438258600194a573f3

- alias: 'interrupteur chambre 1 long clic volet'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033e8984
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_chambre_1 
