#########################################################
# Button bedroom 1 - one click: toggle light            #
#########################################################

- alias: "Button bedroom 1 - one click: toggle light"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033e8984
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.28438258600194a573f3

#########################################################
# Button bedroom 1 - long press: toggle shutters        #
#########################################################

- alias: "Button bedroom 1 - long press: toggle shutters"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00033e8984
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.cover_state_chambre_1

#########################################################
# End                                                   #
#########################################################
