#########################################################
# Sunset +10mn close all shutters                       #
#########################################################

- alias: "Sunset +10mn close all shutters"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:10:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_cuisine
        - switch.cover_state_salon_bas
        - switch.cover_state_salon_haut
        - switch.cover_state_chambre_1

#########################################################
# Sunset +12mn close bedroom shutter                    #
#########################################################

- alias: "Sunset +12mn close bedroom shutter"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:12:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_chambre_2

#########################################################
# Open all shutters in ground floor at 8am (weekday)    #
#########################################################

- alias: "Open all shutters in ground floor at 8am (weekday)"
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_cuisine
        - switch.cover_state_salon_bas
        - switch.cover_state_salon_haut

#########################################################
# Open all shutters in ground floor at 10am (weekend)   #
#########################################################

- alias: "Open all shutters in ground floor at 10am (weekend)"
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_cuisine
        - switch.cover_state_salon_bas
        - switch.cover_state_salon_haut

#########################################################
# Open all shutters in first floor at 10am (weekday)    #
#########################################################

- alias: "Open all shutters in first floor at 10am (weekday)"
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_chambre_1
        - switch.cover_state_chambre_2

#########################################################
# Open all shutters in first floor at 10:30am (weekend) #
#########################################################

- alias: "Open all shutters in first floor at 10:30am (weekend)"
  trigger:
    - platform: time
      at: '10:30:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_chambre_1
        - switch.cover_state_chambre_2

#########################################################
# End                                                   #
#########################################################
