#########################################################
# Home Assistant Start                                  #
#########################################################

- alias: Home Assistant Started
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant Started"
        message: "Home Assistant Has Started"

#########################################################
# Home Assistant Stop                                   #
#########################################################

- alias: Home Assistant Stopped
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.pushbullet
      data:
        title: "Home Assistant Stopped"
        message: "Home Assistant Has Stopped"

#########################################################
# Sensor for low battery                                #
#########################################################

- alias: "Sensor Low Battery"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.bouton_chambre_1
        - sensor.bouton_chambre_2
        - sensor.bouton_cuisine
      below: 20
  action:
    - service: notify.pushbullet
      data_template:
        title: "Home Assistant Device Battery Low"
        message: " The battery for {{ trigger.to_state.attributes.friendly_name }} is below 20 percent."

#########################################################
# End                                                   #
#########################################################
