#########################################################

- alias: Someone enter home
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044993aa
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0003f4ba8d
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.cover_state_salon_haut
            state: 'off'
          - condition: state
            entity_id: switch.cover_state_salon_bas
            state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room

#########################################################
