#########################################################
# Start detecting smoke                                 #
#########################################################

- alias: Start detecting smoke
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_sensor_158d000399007e
      to: 'on'
  action:
    - service: notify.slack
      data:
        title: "Home-Assistant Detect smoke"
        message: "Home-Assistant Smoke detected @channel"
    - service: notify.pushbullet
      data:
        title: "Home-Assistant Detect smoke"
        message: "Home-Assistant Smoke detected"

#########################################################
# Finished detecting smoke                              #
#########################################################

- alias: Finished detecting smoke
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_sensor_158d000399007e
      to: 'off'
  action:
    - service: notify.slack
      data:
        title: "Home-Assistant Detect smoke Finished"
        message: "Home-Assistant Smoke detected Finished"

#########################################################
# End                                                   #
#########################################################
