- alias: "Change ampli volume at 22h for tv"
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: template
      value_template: '{{ states.media_player.onkyo_receiver.attributes.source == TV }}'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.onkyo_receiver
        volume_level: 0.40
