- alias: "Open cover upstair at alarm clock on working days"
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state }}'
    - platform: homeassistant
      event: start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: input_boolean.mode_canicule
        state: 'off'
      - condition: state
        entity_id: input_boolean.alarm_clock_status
        state: 'on'
      - condition: template
        value_template: '{{ states.sensor.time.state >= states.sensor.alarm_clock_time_long.state }}'
      - condition: time
        after: '08:00:00'
        before: '16:00:00'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_bedroom
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_master_bedroom
