- alias: "Open cover upstair at 10h on non working days"
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    - condition: state
      entity_id: input_boolean.mode_canicule
      state: 'off'
    - condition: time
      after: '08:00:00'
      before: '16:00:00'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_bedroom
    - service: switch.turn_on
      entity_id:
        - switch.cover_state_master_bedroom
