#########################################################

- alias: turn off the bathroom light after 20mn
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d00039d4efd
      to: 'on'
      for:
        minutes: 20
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00039d4efd

#########################################################

- alias: turn off the bathroom light after 60mn
  trigger:
    - platform: state
      entity_id: switch.wall_switch_right_158d00039d4efd
      to: 'on'
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00039d4efd

#########################################################
