- alias: "kitchen button switch on tv"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00035a995a
        click_type: single
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_1000a12e98
    - service: switch.turn_on
      entity_id: switch.ampli
    - delay: "00:00:03"
    - service: switch.turn_on
      entity_id: switch.tv
    - service: media_player.select_source
      data:
        entity_id: media_player.onkyo_receiver
        source: 'video2'
    - delay: "00:01:00"
    - service: broadlink.send
      data:
        host: !secret broadlink_host
        packet:
          - "JgDAAFYfEA0MEA8dDR4sHRANDw4PDw0PDw4PDg8PDw4dDhAODxwQDhANDBAPDh4dDg8bEQ4dHR4PDh8MDx0dHRAACMpVHhANDw8LIBAbLBwODxAQDQ8ODhEMEA0PDg8OHg4QDQ8dDg8NEBAODg8dHA8PGxANHx0dDw4eDg8cHR4QAAjJVx0NEBANDxwPHSofDg4PDg8QDg4MEQ8ODw4PDh0ODw8NHw8NDREPDg8OHR0PDhsRDh4dHQ8OHQ8QHB4bEAANBQAAAAAAAAAA" # freebox down
          - "JgDGAFgbEA4QDQ8cDR8sHQ8ODg4PDg8PDRAMEQ8ODRAdDw4OEB0MEA8PDg8QDR0dDg8eDgwgDw4dHR4ODBAOHxAMDwAIylgdEA0ODhAcDR8tGw8OEA4ODg8ODw4PDw8ODw4dDw8ODxwRDg0PDw0QDh0dEA4dDg0eEA4dHR0PDw4PHA8PEAAIyVccDhAODw4dEBssHA4QDw4PDg4PDRAPDg0QDw8dDg8ODx0NEA8QDg4NDx4dDRAdDg8dDw4eHR0ODw4QHA0QDwANBQAA" # freebox ok
    - service: notify.slack
      data:
        message: "tv allumée"
