- alias: "kitchen button switch off tv"
  trigger:
    - platform: state
      entity_id: sensor.kitchen_button_click
      to: 'double'
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states.media_player.onkyo_receiver.attributes.source == Freebox }}'
      - condition: template
        value_template: '{{ states.media_player.onkyo_receiver.attributes.source == TV }}'
  action:
    - service: switch.turn_off
      entity_id: switch.tv_socket
    - delay: "00:00:02"
    - service: input_boolean.turn_off
      entity_id: input_boolean.mode_sport
