- alias: "Switch on coffee machine"
  trigger:
    - platform: state
      entity_id: sensor.kitchen_button_click
      to: 'quadruple'
  action:
    - service: switch.toggle
      entity_id:
        - switch.coffee_socket
