- alias: "dishwasher timer is over"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dishwasher_eco
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.dishwasher
  - service: notify.mobile_app_francois_moto_g_7
    data:
      message: "François, le lave vaisselle est à vider."
  - service: notify.mobile_app_geraldine_moto_g_7
    data:
      message: "Geraldine, le lave vaisselle est à vider."
