- alias: "dishwasher timer is over"
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dishwasher_eco
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.dishwasher
  - service: notify.slack
    data:
      message: "The dishwasher is finished"
