- alias: "kitchen light off nobody present"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044c67d5
      to: 'off'
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d00045fab25
