#########################################################

- alias: "Window kitchen is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003a0f809
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_kitchen
    - service: notify.slack
      data:
        message: "The window in kitchen is open"

#########################################################

- alias: timer finish window open
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.window_kitchen
  action:
    - service: notify.slack
      data:
        message: "Now you can close the window in kitchen"

#########################################################

- alias: "Window kitchen is close"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003a0f809
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_kitchen
    - service: notify.slack
      data:
        message: "The window in kitchen is now closed"

#########################################################
