- alias: "kitchen window is close"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_kitchen
