- alias: "kitchen window is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_kitchen
