- alias: "kitchen window is still open and the timer is over"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.window_kitchen
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "Now you can close the window in kitchen"
