- alias: "kitchen window is close"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003a0f809
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.window_kitchen
    - service: notify.slack
      data:
        message: "The window in kitchen is now closed"
