- alias: "kitchen window is open"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003a0f809
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.window_kitchen
    - service: notify.slack
      data:
        message: "The window in kitchen is open"
