- alias: 'Alarme déclenchée'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'triggered'
  action:
    - service: notify.slack
      data:
        message: '@channel Alarme !!!'
    - service: script.turn_on
      entity_id: script.start_alarm
    - service: script.turn_on
      entity_id: script.flash_light
