- alias: 'stop alarm'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.disable_alarm
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data_template:
        option: "{{ input_select.house_mode }}"
