- alias: 'Alarme enclenchée (absence)'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'armed_away'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_socket
    - service: notify.slack
      data:
        message: 'Alarme enclenchée (absence)'
