- alias: 'Alarme enclenchée (absence)'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'armed_away'
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: 'Alarme enclenchée (absence)'
