#pending_time (lorsque l'on active l'alarme elle se met en pending pendant le temps de pending time indiqué puis passe à l'état armée)
#quand l'alarme est déclanché pendant delay_time+pending_time
- alias: "Porte ou fenetre ouverte quand alarme active"
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00039fe3a9 # fenetre salon
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003a0f809 # fenetre salle a manger
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003f41fe9 # fenetre chambre 1
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003f4baa8 # fenetre chambre 2
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0003f4ba8d # porte entrée
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.home
          state: armed_home
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home

- alias: 'Alarme enclenchée (absence)'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'armed_away'
  action:
    - service: switch.turn_on
      entity_id: switch.camera_socket
    - service: notify.slack
      data:
        message: 'Alarme enclenchée (absence)'

- alias: 'Alarme enclenchée (présent)'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'armed_home'
  action:
    - service: notify.slack
      data:
        message: 'Alarme enclenchée (présent)'

- alias: 'Alarme déclenchée'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'triggered'
  action:
    - service: notify.slack
      data:
        message: '@channel Alarme !!!'
    - service: script.turn_on
      entity_id: script.start_alarm
    - service: script.turn_on
      entity_id: script.flash_light

- alias: 'Alarme désactivée'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'disarmed'
  action:
    - service: notify.slack
      data:
        message: 'Alarme désactivée'
    - service: script.turn_off
      entity_id: script.start_alarm
    - service: script.turn_off
      entity_id: script.flash_light
    - service: xiaomi_aqara.stop_ringtone
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data_template:
        option: "{{ input_select.house_mode }}"

- alias: 'stop alarm'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.disable_alarm
    to: 'off'
  action:
    - service: xiaomi_aqara.stop_ringtone
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data_template:
        option: "{{ input_select.house_mode }}"
