- alias: 'Alarme désactivée'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.home
    to: 'disarmed'
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "François, Alarme désactivée."
    - service: input_select.select_option
      entity_id: input_select.house_mode
      data_template:
        option: "{{ input_select.house_mode }}"
