#########################################################

- alias: Home-Assistant Started
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.slack
      data:
        title: "Home-Assistant Started"
        message: "Home-Assistant Has Started"

#########################################################

- alias: Home-Assistant Stopped
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.slack
      data:
        title: "Home-Assistant Stopped"
        message: "Home-Assistant Has Stopped"

#########################################################
