- alias: Home-Assistant Started
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "François, home assistant a démarré."
    - service: var.set
      data:
        entity_id:
          - var.francois_in_bedroom
        value: 0
    - service: var.set
      data:
        entity_id:
          - var.geraldine_in_bedroom
        value: 0
