- alias: Home-Assistant Stopped
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.mobile_app_francois_moto_g_7
      data:
        message: "François, home assistant s'est arrété."
