- alias: Set 'away' by hand
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'away'
  action:
    - service: switch.turn_off
      entity_id:
        - group.lights
        - group.sockets
    - service: light.turn_off
      entity_id:
        - light.living_room
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_04cf8cb87b01
        brightness_pct: 2
        color_name: red
    - service: switch.turn_on
      entity_id: switch.camera_socket
