#########################################################

- alias: Someone enter home
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00044993aa
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0003f4ba8d
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.cover_state_mezzanine
            state: 'off'
          - condition: state
            entity_id: switch.cover_state_living_room
            state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d00045f9e86

#########################################################
