- alias: "Person as away"
  trigger:
    - platform: state
      entity_id: input_select.francois_status_dropdown
      to: 'just left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.geraldine_status_dropdown
      to: 'just left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.francois_status_dropdown' %}
            input_select.francois_status_dropdown
          {% else %}
            input_select.geraldine_status_dropdown
          {% endif %}
        option: away
