- alias: Someone enter home switch on the entrance light
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.entrance_door
        state: 'on'
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.cover_state_mezzanine
            state: 'off'
          - condition: state
            entity_id: switch.cover_state_living_room
            state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.entrance_light
