- alias: switch rdc
  trigger:
    - platform: state
      entity_id: input_boolean.switch_rdc
      to: 'off'
  action:
    - service_template: "switch.turn_off"
      entity_id:
        - group.lights_rdc
    - service_template: "light.turn_off"
      entity_id:
        - group.light_rdc
