- alias: switch r1
  trigger:
    - platform: state
      entity_id: input_boolean.switch_r1
      to: 'off'
  action:
    - service_template: "switch.turn_off"
      entity_id:
        - group.lights_r1
    - service_template: "light.turn_off"
      entity_id:
        - group.light_r1
