- alias: Vacuum docked
  trigger:
    - platform: state
      entity_id: vacuum.vacuum_up
      to: 'docked'
    - platform: state
      entity_id: vacuum.vacuum_down
      to: 'docked'
  action:
    - service: notify.slack
      data_template:
        message: "Vacuum {{ trigger.entity_id }} is now docked"
