- alias: Vacuum r0
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Away'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: vacuum.start
      entity_id: vacuum.vacuum_down
    - service: notify.slack
      data:
        message: "Vacuum up start cleaning"
