#########################################################

- alias: "Sunset close downstair covers"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:00:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_kitchen
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_living_room
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_mezzanine
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_bedroom_1
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_bedroom_2

#########################################################
