#########################################################

- alias: "Sunset +10mn close all shutters"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:10:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_cuisine
        - switch.cover_state_salon_bas
        - switch.cover_state_salon_haut
        - switch.cover_state_chambre_1

#########################################################

- alias: "Sunset +10mn10 close bedroom shutter"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:10:10'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.cover_state_chambre_2

#########################################################
