#########################################################

- alias: "Sunset +10mn close downstair covers"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:10:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.downstair_covers

#########################################################

- alias: "Sunset +11mn close upstair covers"
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:11:00'
  condition:
    - condition: time
      after: '16:00:00'
      before: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.upstair_covers

#########################################################
