#########################################################

- alias: "Open all shutters in ground floor at 9am (weekend)"
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.downstair_covers

#########################################################

- alias: "Open all shutters in first floor at 10:00am (weekend)"
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.upstair_covers

#########################################################
