- alias: "test cover on"
  trigger:
    - platform: time
      at: '13:14:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.test_cover_state_kitchen

- alias: "test cover on 2"
  trigger:
    - platform: time
      at: '13:15:00'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.test_cover_state_living_room_top
        - switch.test_cover_state_living_room_bottom

